name: wetrek
description: A Social Media for Trekkers where people who walk can connect

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^4.1.2
  json_to_model: ^2.3.0
  animations: ^2.0.0
  equatable: ^2.0.2
  http: ^0.13.3
  flutter_secure_storage: ^4.2.0
  flutter_bloc: ^7.0.0
  formz: ^0.4.0
  # fluttericon:
  google_maps_flutter: ^2.0.6
  geolocator: ^7.2.0+1
  laravel_echo: ^1.0.0-beta.1
  # flutter_pusher: ^1.0.3
  pusher_client: ^2.0.0
  rxdart: ^0.27.1
  timeago: ^3.1.0
#  geolocator: ^7.0.3
#  geocoding: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  flutter_launcher_icons: 

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"
# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/marker.png
     - images/map.png
     - images/dark_map.png
     - images/sushi.jpg
     - images/ice_cream.jpg
     - images/museum.jpg
     - images/avatar1.jpg
     - images/avatar2.jpg
     - images/avatar3.jpg
     - images/avatar4.jpg
     - .env
     - assets/map_style.txt

  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family:  Gibson
      fonts:
        - asset: fonts/Gibson-Regular.ttf
        - asset: fonts/gibson-bold.ttf
          weight: 700
        - asset: fonts/Gibson-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Gibson-RegularItalic.ttf
          style: italic
    - family: Martel Sans
      fonts:
              - asset: fonts/MartelSans-Regular.ttf
              - asset: fonts/MartelSans-Bold.ttf
                weight: 700
              - asset: fonts/MartelSans-ExtraBold.ttf
                weight: 800
              - asset: fonts/MartelSans-ExtraLight.ttf
                weight: 200
              - asset: fonts/MartelSans-Light.ttf
                weight: 300
              - asset: fonts/MartelSans-SemiBold.ttf
                weight: 500
